name: CI
on:
  pull_request:
    branches: [ main ]
jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with: { version: 9 }
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - run: pnpm install
      - run: pnpm -r build --if-present
      - run: pnpm -r test --if-present
      - run: pnpm -r lint --if-present
